INSERT INTO inventory (userId, vehicleId, partName, description, price, datecreated)
VALUES
	(1, 1, 'Alternator', 'New Alternator, bought the thign thten stoafewiogwlkagle', 70, '2017-05-28'),
  (2, 2354, 'Alternator', 'Used Alternator, bought the thign thten stoafewiogwlkagle', 40.99, '2017-05-30'),
  (2, 15232, 'Alternator', 'Used Alternator, bought the thign thten stoafewiogwlkagle', 40.95, '2017-06-01'),
  (3, 490, 'Alternator', 'Newer Alternator, bought the thign thten stoafewiogwlkagle', 100, '2017-06-05'),
  (3, 3490, 'Alternator', 'Newer Alternator, bought the thign thten stoafewiogwlkagle', 105.75, '2017-06-06');
